### PR TITLE
build|docs: Migrate from *.workflow to v2 *.yml GitHub Actions syntax.

### PR DESCRIPTION
**Pull request by adyavanapalli**
I was working on a hobby project that used this particular GitHub Action and noticed it could use updating. I've used the [migration tool](https://github.com/actions/migrate) to implement these changes.

### CODE REVIEW

**Comment by adyavanapalli** [comment]
@parkr, @anthonysterling, @max, @hfaulds, @thepwagner
Just bumping this PR so it's merged in more quickly.

**Comment by adyavanapalli** [comment]
@parkr, @anthonysterling, @max, @hfaulds, @thepwagner
Bumping this PR again so it's merged in more quickly.

**Comment by adyavanapalli** [comment]
@parkr, @anthonysterling, @max, @hfaulds, @thepwagner
Hey, it's me. Your forgotten PR. Please look at me.

**Comment by anthonysterling** [comment]
Thanks @adyavanapalli and apologies for the wait, we're all super busy in the run up to Universe 2019. 😄

**Comment by adyavanapalli** [comment]
@anthonysterling Thank you!

**Pull request merged**
